# Generated by Django 3.1.7 on 2021-06-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('breakfast', '朝食'), ('lunch', '昼食'), ('dinner', '夕食')], default='none', max_length=200),
            preserve_default=False,
        ),
    ]
