# Generated by Django 3.1.7 on 2021-06-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210620_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_public',
            field=models.CharField(choices=[('公開', '公開'), ('非公開', '非公開')], max_length=200, verbose_name='公開設定'),
        ),
    ]
