# Generated by Django 3.1.7 on 2021-06-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210620_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
