# Generated by Django 3.1.7 on 2021-06-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210614_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('breakfast', '朝食'), ('lunch', '昼食'), ('dinner', '夕食')], default='none', max_length=200),
            preserve_default=False,
        ),
    ]
