# Generated by Django 3.1.7 on 2021-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210615_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('breakfast', '朝食'), ('lunch', '昼食'), ('snack', '間食'), ('dinner', '夕食')], max_length=200),
        ),
    ]
