# Generated by Django 3.1.7 on 2021-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210615_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('朝食', '朝食'), ('昼食', '昼食'), ('間食', '間食'), ('夕食', '夕食')], max_length=200),
        ),
    ]
