# Generated by Django 3.1.7 on 2021-06-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('朝食', '朝食'), ('昼食', '昼食'), ('夕食', '夕食'), ('間食', '間食')], max_length=200),
        ),
        migrations.AlterField(
            model_name='target',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
