# Generated by Django 3.1.7 on 2021-06-26 04:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_auto_20210625_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('kcal', models.PositiveSmallIntegerField(verbose_name='カロリー')),
                ('protein', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='タンパク質')),
                ('fat', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='脂質')),
                ('carb', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='炭水化物')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
