# Generated by Django 3.1.7 on 2021-06-27 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='category',
            field=models.CharField(choices=[('朝食', '朝食'), ('昼食', '昼食'), ('夕食', '夕食'), ('間食', '間食')], default=django.utils.timezone.now, max_length=200, verbose_name='カテゴリー'),
            preserve_default=False,
        ),
    ]
