# Generated by Django 3.2.4 on 2022-01-25 22:52

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_auto_20210727_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='carb',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='carb'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=200, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='fat'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='kcal',
            field=models.PositiveSmallIntegerField(verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='Protein'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carb',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='carb'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=200, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='food',
            name='eaten_date',
            field=models.DateField(default=datetime.date.today, help_text='※yyyy-mm-dd', verbose_name='eaten date'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='fat'),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal',
            field=models.PositiveSmallIntegerField(verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='Protein'),
        ),
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='target',
            name='carb',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='carb'),
        ),
        migrations.AlterField(
            model_name='target',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='target',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='fat'),
        ),
        migrations.AlterField(
            model_name='target',
            name='kcal',
            field=models.PositiveSmallIntegerField(verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='target',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(999.9), django.core.validators.MinValueValidator(0.0)], verbose_name='Protein'),
        ),
        migrations.AlterField(
            model_name='target',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
